language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "3.6"

install:
  - pip3 install -U pip wheel
  - pip3 install numpy
  - pip3 install -r ./tools/test_requirements.txt
  - pip3 install -r ./tools/requirements.txt
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip3 install torchvision
  - git clone https://github.com/k2kobayashi/sprocket.git
  - cd sprocket
  - pip3 install -r requirements.txt
  - python setup.py install
  - cd ../

script:
  - flake8 src test
  - autopep8 -r src test --exclude src/utils --global-config .pep8 --diff --max-line-length 120 | tee check_autopep8
  - test ! -s check_autopep8
  - pytest

sudo: false

addons:
  apt:
    packages:
      - cmake
      - python3-dev
